=== Basmalahasad/assignment-1--databases--cs-365--fall-2024/xml/student.dtd
<!-- ====================================================================
  Define the root element of the XML document, student-records is a
  container for one or more student elements.
  ================================================================== -->
<!ELEMENT student-records (student)+>

<!-- ===================================================================
  Define the structure of a student element, where each student must
  have first and last name, student ID, email, phone, year, GPA,
  major, status, advisor, enrollment date, graduation date elements.

  The student can have zero or one middle name and preferred name.

  The student can have zero or more minors and one or more majors.
  ================================================================== -->
<!ELEMENT student (first-name,middle-name?,last-name,preferred-name?,student-id,email,phone,year,gpa,major+,minor*,status,advisor,date-of-enrollment,date-of-graduation)>

<!-- Define the first-name element, which contains text. -->
<!ELEMENT first-name (#PCDATA)>
<!-- Define the middle-name element, which contains text and is optional. -->
<!ELEMENT middle-name (#PCDATA)>
<!-- Define the last-name element, which contains text. -->
<!ELEMENT last-name (#PCDATA)>
<!-- Define the preferred-name element, which contains text and is optional. -->
<!ELEMENT preferred-name (#PCDATA)>
<!-- Define the student-id element, which contains text. -->
<!ELEMENT student-id (#PCDATA)>
<!-- Define the email element, which contains text. -->
<!ELEMENT email (#PCDATA)>
<!-- Define the phone element, which contains text. -->
<!ELEMENT phone (#PCDATA)>
<!-- Define the year element, which contains text. -->
<!ELEMENT year (#PCDATA)>
<!-- Define the GPA element, which contains text. -->
<!ELEMENT gpa (#PCDATA)>
<!-- Define the major element, which contains text and can appear one or more times -->
<!ELEMENT major (#PCDATA)>
<!-- Define the minor element, which contains text and is optional. -->
<!ELEMENT minor (#PCDATA)>
<!-- Define the status element, which contains text. -->
<!ELEMENT status (#PCDATA)>
<!-- Define the advisor element, which contains text. -->
<!ELEMENT advisor (#PCDATA)>
<!-- Define the date-of-enrollment element, which contains text. -->
<!ELEMENT date-of-enrollment (#PCDATA)>
<!-- Define the date-of-graduation element, which contains text. -->
<!ELEMENT date-of-graduation (#PCDATA)>

<!-- ====================================================================
  Define the attributed for the student element.

  Year attribute must be one of : first-year, second-year, third-year,
  fourth-year, or graduate.

  status attribute must be one of : full-time, part-time, graduated,
  withdrawn.

  Both atributes are required.
  ================================================================== -->
<!ATTLIST student
          year (first-year | second-year | third-year | fourth-year | graduate) #REQUIRED
          status (full-time | part-time | graduated | withdrawn) #REQUIRED
>

=== Basmalahasad/assignment-1--databases--cs-365--fall-2024/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE student-records SYSTEM "student.dtd">

<student-records>
  <student name="Gordon Matthew Sumner">
    <preferred-name>Sting</preferred-name>
    <student-id>1234567</student-id>
    <email>sting@thepolice.com</email>
    <phone>212.123.4567</phone>
  </student>
  <student name="Kim Thayil">
    <student-id>4567890</student-id>
    <email>kim@soundgarden.com</email>
    <phone>206.123.4567</phone>
  </student>
  <student name="Saul Hudson">
    <preferred-name>Slash</preferred-name>
    <student-id>8302438</student-id>
    <email>slash@gnr.com</email>
    <phone>213.456.8392</phone>
  </student>
  <student name="Emily Kokal">
    <student-id>2983928</student-id>
    <email>emily@warpaint.com</email>
    <phone>213.123.7654</phone>
  </student>
  <student name="Mike Inez">
    <student-id>7645726</student-id>
    <email>mike@aic.com</email>
    <phone> 213.444.3323</phone>
  </student>
</student-records>
